apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: managed-standard
  azureDisk:
    diskName: grafana-pv
    diskURI: "/subscriptions/cea4f1ae-dff5-4428-bab7-e5139042bc8a/resourceGroups/cloud-computing-gp/providers/Microsoft.Compute/disks/grafana-pv"
    kind: Managed
    fsType: ext4
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bookstore-grafana
  namespace: bookstore
spec:
  serviceName: bookstore-grafana
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-grafana
  template:
    metadata:
      labels:
        app: bookstore-grafana
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: grafana
          image: cloudgp.azurecr.io/bookstore-graphana
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
  volumeClaimTemplates:
    - metadata:
        name: grafana-storage
        namespace: bookstore
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: managed-standard
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-grafana
  namespace: bookstore
spec:
  selector:
    app: bookstore-grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000