apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-prometheus
  namespace: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-prometheus
  template:
    metadata:
      labels:
        app: bookstore-prometheus
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: prometheus
          image: cloudgp.azurecr.io/bookstore-prometheus
          ports:
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-prometheus
  namespace: bookstore
spec:
  selector:
    app: bookstore-prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090