kind: Deployment
metadata:
  name: bookstore-catalog-service
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: my-app  
  template:
    metadata:
      labels:
        app: my-app  
    spec:
      containers:
      - name: my-app-container  # Change to a container name
        image: myregistry.azurecr.io/my-app:latest  # Replace with  Azure Container Registry (ACR) image
        ports:
        - containerPort: 6001  
