apiVersion: v1
kind: Service
metadata:
  name: bookstore-catalog-service
spec:
  selector:
    app: my-app  
  ports:
    - protocol: TCP
      port: 80  # This is the external port to access the application
      targetPort: 6001  #  containerPort in deployment.yaml
  type: LoadBalancer  # Useing LoadBalancer for external access