apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: managed-standard
  azureDisk:
    diskName: influxdb-pv
    diskURI: "/subscriptions/cea4f1ae-dff5-4428-bab7-e5139042bc8a/resourceGroups/cloud-computing-gp/providers/Microsoft.Compute/disks/influxdb-pv"
    kind: Managed
    fsType: ext4
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bookstore-influxdb
  namespace: bookstore
spec:
  serviceName: bookstore-influxdb
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-influxdb
  template:
    metadata:
      labels:
        app: bookstore-influxdb
    spec:
      containers:
        - name: influxdb
          image: influxdb
          ports:
            - containerPort: 8086
          volumeMounts:
            - name: influxdb-data
              mountPath: /var/lib/influxdb
  volumeClaimTemplates:
    - metadata:
        name: influxdb-data
        namespace: bookstore
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: managed-standard
        resources:
          requests:
            storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-influxdb
  namespace: bookstore
spec:
  selector:
    app: bookstore-influxdb
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086