apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-kapacitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-kapacitor
  template:
    metadata:
      labels:
        app: bookstore-kapacitor
    spec:
      containers:
        - name: kapacitor
          image: kapacitor
          env:
            - name: KAPACITOR_HOSTNAME
              value: "bookstore-kapacitor"
            - name: KAPACITOR_INFLUXDB_0_URLS_0
              value: "http://bookstore-influxdb:8086"
          ports:
            - containerPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-kapacitor
spec:
  selector:
    app: bookstore-kapacitor
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092