apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-billing-service
  namespace: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-billing-service
  template:
    metadata:
      labels:
        app: bookstore-billing-service
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: bookstore-billing-service
          image: cloudgp.azurecr.io/bookstore-billing-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
          env:
            - name: SERVER_PORT
              value: "5001"
            - name: ZIPKIN_HOST
              value: "bookstore-zipkin:9411"
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
#          resources:
#            requests:
#              memory: "256Mi"
#              cpu: "200m"
#            limits:
#              memory: "512Mi"
#              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-billing-service
  namespace: bookstore
spec:
  selector:
    app: bookstore-billing-service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001