apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-order-service
  namespace: bookstore
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-order-service
  template:
    metadata:
      labels:
        app: bookstore-order-service
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: bookstore-order-service
          image: bookstoreapplicationregistry.azurecr.io/bookstore-order-service:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 7001
          env:
            - name: SERVER_PORT
              value: "7001"
            - name: ZIPKIN_HOST
              value: "bookstore-zipkin:9411"
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 7001
            initialDelaySeconds: 40
            periodSeconds: 10
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 7001
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
#          resources:
#            requests:
#              memory: "128Mi"
#              cpu: "100m"
#            limits:
#              memory: "512Mi"
#              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-order-service
  namespace: bookstore
spec:
  selector:
    app: bookstore-order-service
  ports:
    - protocol: TCP
      port: 7001
      targetPort: 7001