apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-catalog-service-blue
  namespace: bookstore
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookstore-catalog-service
      version: blue
  template:
    metadata:
      labels:
        app: bookstore-catalog-service
        version: blue
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: bookstore-catalog-service
          image: bookstoreapplicationregistry.azurecr.io/bookstore-catalog-service:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 6001
          env:
            - name: SERVER_PORT
              value: "6001"
            - name: ZIPKIN_HOST
              value: "bookstore-zipkin:9411"
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: JAVA_OPTS
              value: "-Xms512m -Xmx1024m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ActiveProcessorCount=2"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "1024Mi"
              cpu: "800m"

