apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-order-service
  namespace: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-order-service
  template:
    metadata:
      labels:
        app: bookstore-order-service
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: bookstore-order-service
          image: cloudgp.azurecr.io/bookstore-order-service:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 7001
          env:
            - name: SERVER_PORT
              value: "7001"
            - name: ZIPKIN_HOST
              value: "bookstore-zipkin:9411"
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 7001
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 7001
            initialDelaySeconds: 10
            periodSeconds: 5
#          resources:
#            requests:
#              memory: "256Mi"
#              cpu: "200m"
#            limits:
#              memory: "512Mi"
#              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-order-service
  namespace: bookstore
spec:
  selector:
    app: bookstore-order-service
  ports:
    - protocol: TCP
      port: 7001
      targetPort: 7001