apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-account-service
  namespace: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-account-service
  template:
    metadata:
      labels:
        app: bookstore-account-service
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: bookstore-account-service
          image: cloudgp.azurecr.io/bookstore-account-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4001
          env:
            - name: SERVER_PORT
              value: "4001"
            - name: ZIPKIN_HOST
              value: "bookstore-zipkin:9411"
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
#          resources:
#            requests:
#              memory: "256Mi"
#              cpu: "200m"
#            limits:
#              memory: "512Mi"
#              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-account-service
  namespace: bookstore
spec:
  selector:
    app: bookstore-account-service
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001