apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-api-gateway-service
  namespace: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-api-gateway-service
  template:
    metadata:
      labels:
        app: bookstore-api-gateway-service
    spec:
      containers:
        - name: bookstore-api-gateway-service
          image: bookstoreapplicationregistry.azurecr.io/bookstore-api-gateway-service:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 8765
          env:
            - name: SERVER_PORT
              value: "8765"
            - name: ZIPKIN_HOST
              value: "bookstore-zipkin:9411"
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-api-gateway-service
  namespace: bookstore
spec:
  selector:
    app: bookstore-api-gateway-service
  ports:
    - protocol: TCP
      port: 8765
      targetPort: 8765