apiVersion: v1
kind: Service
metadata:
  name: bookstore-catalog-service
  namespace: bookstore
spec:
  selector:
    app: bookstore-catalog-service
    version: blue
  ports:
    - protocol: TCP
      port: 6001
      targetPort: 6001
