apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-payment-service
  namespace: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-payment-service
  template:
    metadata:
      labels:
        app: bookstore-payment-service
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: bookstore-payment-service
          image: cloudgp.azurecr.io/bookstore-payment-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          env:
            - name: SERVER_PORT
              value: "8001"
            - name: ZIPKIN_HOST
              value: "bookstore-zipkin:9411"
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-payment-service
  namespace: bookstore
spec:
  selector:
    app: bookstore-payment-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001