apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-catalog-service
  namespace: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-catalog-service
  template:
    metadata:
      labels:
        app: bookstore-catalog-service
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: bookstore-catalog-service
          image: cloudgp.azurecr.io/bookstore-catalog-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 6001
          env:
            - name: SERVER_PORT
              value: "6001"
            - name: ZIPKIN_HOST
              value: "bookstore-zipkin:9411"
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-catalog-service
  namespace: bookstore
spec:
  selector:
    app: bookstore-catalog-service
  ports:
    - protocol: TCP
      port: 6001
      targetPort: 6001