apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-agent
  namespace: velero
spec:
  selector:
    matchLabels:
      name: node-agent
  template:
    metadata:
      labels:
        component: velero
        name: node-agent
    spec:
      containers:
        - name: node-agent
          resources:
            limits:
              cpu: "100m"
              memory: "128Mi"
            requests:
              cpu: "50m"
              memory: "64Mi"

  