name: CD Pipeline - Java 11

on:
  workflow_run:
    workflows: ["CI Pipeline - Java 11"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [bookstore-api-gateway-service, bookstore-eureka-discovery-service, bookstore-account-service, bookstore-billing-service, bookstore-catalog-service, bookstore-order-service, bookstore-payment-service]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download built artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.service }}-artifact
          path: ./services/${{ matrix.service }}/target

      - name: Build Docker Image
        run: |
          docker build -t my-docker-repo/${{ matrix.service }}:latest ./services/${{ matrix.service }}

      - name: Push Docker Image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push my-docker-repo/${{ matrix.service }}:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ./services/${{ matrix.service }}/k8s/deployment.yml
          kubectl rollout status deployment/${{ matrix.service }}
