name: Frontend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: bookstore-frontend-react-app/package-lock.json
      - working-directory: bookstore-frontend-react-app
        run: npm install --force
      - working-directory: bookstore-frontend-react-app
        run: npm run build

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=$(git rev-parse --short HEAD)
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/bookstore-frontend-react-app:latest bookstore-frontend-react-app
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/bookstore-frontend-react-app:latest

      - name: Archive built frontend artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bookstore-frontend-react-app-build
          path: bookstore-frontend-react-app/build