name: CI Pipelines

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-commons:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        commons: [bookstore-commons, bookstore-feign]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Build and Install ${{matrix.commons}}
        working-directory: ${{matrix.commons}}
        run: mvn clean install -DskipTests=true

      - name: Upload ${{matrix.commons}} artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.commons}}
          path: ~/.m2/repository/com/devd/spring/${{matrix.commons}}/

  download-commons:
    needs: build-commons
    runs-on: ubuntu-latest
    strategy:
      matrix:
        commons: [bookstore-commons, bookstore-feign ]

    steps:
      - name: Download ${{matrix.commons}} artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{matrix.commons}}
          path: ~/.m2/repository/com/devd/spring/${{matrix.commons}}/

  build-frontend:
    runs-on: ubuntu-latest
    needs: download-commons
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js and NVM
        run: |
          curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install 16
          nvm use 16
          node -v
          npm -v

      - name: Install dependencies
        working-directory: bookstore-frontend-react-app
        run: npm install postcss-safe-parser@latest postcss@latest --legacy-peer-deps

      - name: Set OpenSSL Legacy Provider
        run: export NODE_OPTIONS=--openssl-legacy-provider

      - name: Build React App
        working-directory: bookstore-frontend-react-app
        run: npm run build

      - name: Archive built frontend artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bookstore-frontend-react-app-build
          path: bookstore-frontend-react-app/build

  build-services:
    needs: download-commons
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [bookstore-api-gateway-service, bookstore-eureka-discovery-service, bookstore-account-service, bookstore-billing-service, bookstore-catalog-service, bookstore-order-service, bookstore-payment-service]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Download ${{matrix.commons}} artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{matrix.commons}}
          path: ~/.m2/repository/com/devd/spring/${{matrix.commons}}/

      - name: Build and Test ${{ matrix.service }}
        working-directory: ${{ matrix.service }}
        run: mvn clean install -DskipTests=false

      - name: Archive built artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.service }}-artifact
          path: ${{ matrix.service }}/target/*.jar
