name: Deploy order service

on:
  workflow_run:
    workflows:
      - CI Pipelines
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS Context
        run: az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Install envsubst
        run: |
          sudo apt-get update
          sudo apt-get install -y gettext-base

      - name: Set environment variables
        run: |
          export IMAGE_TAG=$(git rev-parse --short HEAD)
          echo "IMAGE_TAG: $IMAGE_TAG"

      - name: Replace variables in Kubernetes manifest
        run: |
          export IMAGE_TAG=$(git rev-parse --short HEAD)
          envsubst < ./kubernetes/services/bookstore-order-service.yaml > ./kubernetes/services/bookstore-order-service-substituted.yaml

      - name: Force delete old bookstore-order-service pods
        run: |
          kubectl scale deployment bookstore-order-service --replicas=0
          echo "Waiting for all old bookstore-order-service pods to terminate..."
          kubectl get pods -n bookstore | grep bookstore-order-service
          sleep 10
          kubectl scale deployment bookstore-order-service --replicas=1

      - name: Deploy Order Service
        run: |
          kubectl apply -f ./kubernetes/services/bookstore-order-service-substituted.yaml

      - name: Wait for Deployment to complete
        run: |
          echo "Waiting for deployment to complete..."
          kubectl rollout status deployment bookstore-order-service -n bookstore --timeout=120s

      - name: Verify Pod readiness
        run: |
          echo "Waiting for all bookstore-order-service pods to be ready..."
          kubectl wait --for=condition=Ready pod -l app=bookstore-order-service -n bookstore --timeout=60s

      - name: Rollback on Failure
        if: failure()
        run: |
          if kubectl rollout history deployment/bookstore-order-service -n bookstore | grep -q "REVISION"; then
            echo "Rolling back bookstore-order-service..."
            kubectl rollout undo deployment bookstore-order-service -n bookstore
          else
            echo "No rollback history found, skipping..."
          fi
