apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: managed-standard
  azureDisk:
    diskName: postgresql-pv
    diskURI: "/subscriptions/7ef20365-f671-469f-af5c-e139c62374e0/resourceGroups/cloud-computing-gp/providers/Microsoft.Compute/disks/postgresql-pv"
    kind: Managed
    fsType: ext4
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bookstore-pgsql-db
  namespace: bookstore
spec:
  serviceName: bookstore-pgsql-db
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-pgsql-db
  template:
    metadata:
      labels:
        app: bookstore-pgsql-db
    spec:
      nodeSelector:
        db-node: "true"
      containers:
        - name: postgres
          image: postgres:14
          env:
            - name: POSTGRES_DB
              value: "bookstore_db"
            - name: POSTGRES_PASSWORD
              value: "PaSSworD"
            - name: PGDATA
              value: "/var/lib/postgresql/data/bookstore"
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgresql-data
        namespace: bookstore
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: managed-standard
        resources:
          requests:
            storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-pgsql-db
  namespace: bookstore
spec:
  clusterIP: None
  selector:
    app: bookstore-pgsql-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432