apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: bookstore
data:
  POSTGRES_DB: "bookstore_db"
  POSTGRES_USER: "postgres"

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bookstore-pgsql-db
  namespace: bookstore
spec:
  serviceName: bookstore-pgsql-db
  replicas: 3
  selector:
    matchLabels:
      app: bookstore-pgsql-db
  template:
    metadata:
      labels:
        app: bookstore-pgsql-db
    spec:
      containers:
        - name: postgres
          image: postgres:14
          envFrom:
            - configMapRef:
                name: postgres-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: "/var/lib/postgresql/data/bookstore"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/bookstore
          resources:
            limits:
              cpu: "2"
              memory: "2Gi"
            requests:
              cpu: "1"
              memory: "1Gi"
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-pgsql-db
  namespace: bookstore
spec:
  selector:
    app: bookstore-pgsql-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP